// Trait catalog adapter — thin layer over public/sprites/limezu/manifest.json.
//
// The manifest is generated by `scripts/import-limezu.mjs` from the vendored
// LimeZu Modern Interiors Character Generator pack. Adding/removing trait
// options is a manifest change, not a code change.

import type { Category, Direction, TrainerConfig, TrainerOption } from '@/types/trainer';
import manifest from '../../public/sprites/limezu/manifest.json';

// ---- manifest types (loose — matches the generated JSON shape) ----
interface ManifestValue {
  id: string;
  label?: string;
  file?: string;
  baseId?: string;     // for outfit/accessory: source ID before -<variant> suffix (used by importer; not consumed at render time)
  variant?: string;
  hex?: string;
}
interface ManifestCategory {
  values: ManifestValue[];
  optional?: boolean;
  supportsColor?: boolean;
}
interface Manifest {
  version: number;
  source?: string;
  spriteWidth: number;
  spriteHeight: number;
  directions?: Direction[] | null;
  defaultDirection?: Direction | null;
  bustCrop: { x: number; y: number; w: number; h: number };
  categories: Record<string, ManifestCategory>;
}
const MANIFEST = manifest as Manifest;

// ---- public surface ----

export interface TraitCategory {
  key: keyof TrainerConfig;
  label: string;
  options: TrainerOption[];
  /** True when the user MUST pick a value before Generate is allowed. */
  required: boolean;
}

const CATEGORY_LABELS: { key: keyof TrainerConfig; label: string }[] = [
  { key: 'body',      label: 'Skin' },
  { key: 'eyes',      label: 'Eyes' },
  { key: 'hair',      label: 'Hair' },
  { key: 'hairColor', label: 'Hair Color' },
  { key: 'outfit',    label: 'Outfit' },
  { key: 'accessory', label: 'Accessory' },
];

// Required-for-generate categories — empty string blocks Generate.
// Optional categories (eyes, accessory) use 'none' as the "not picked" sentinel.
export const REQUIRED_FOR_GENERATE: ReadonlyArray<keyof TrainerConfig> = [
  'body', 'hair', 'hairColor', 'outfit',
];

const REQUIRED_SET: ReadonlySet<string> = new Set<string>(REQUIRED_FOR_GENERATE as readonly string[]);

function manifestToOptions(cat: ManifestCategory | undefined): TrainerOption[] {
  if (!cat) return [];
  return cat.values.map((v) => ({ id: v.id, label: v.label ?? v.id }));
}

export const CATEGORIES: TraitCategory[] = CATEGORY_LABELS.map(({ key, label }) => {
  const cat = MANIFEST.categories[key as Category];
  return {
    key,
    label,
    options: manifestToOptions(cat),
    required: REQUIRED_SET.has(key),
  };
});

export const INITIAL_CONFIG: TrainerConfig = {
  body: '',
  hair: '',
  hairColor: '',
  outfit: '',
  eyes: 'none',
  accessory: 'none',
};

export function isReadyToGenerate(config: TrainerConfig): boolean {
  for (const key of REQUIRED_FOR_GENERATE) {
    const value = config[key];
    if (!value || value === 'none') return false;
  }
  return true;
}

// ---- sprite-path helpers ----
//
// LimeZu paper-doll paths (rendered lowest-first):
//   body      /sprites/limezu/body/<id>-<dir>.png
//   outfit    /sprites/limezu/outfit/<id>/<variant>-<dir>.png
//   eyes      /sprites/limezu/eyes/<id>-<dir>.png
//   hair      /sprites/limezu/hair/<style>/<color>-<dir>.png
//   accessory /sprites/limezu/accessory/<id>/<variant>-<dir>.png
//
// <dir> is one of 's', 'e', 'w', 'n'. South ('s') is the default for share
// cards and the customizer preview.
//
// Outfit/accessory IDs from the manifest are flattened slugs `<baseId>-<variant>`
// (e.g. "01-02"). The flattened slug is the renderer's interface — the importer
// records the split via baseId/variant on the manifest entry, but renderers
// don't need to know the split. We look up the entry to read baseId+variant.

const ROOT = '/sprites/limezu';
const HAS_DIRECTIONS = Boolean(MANIFEST.directions && MANIFEST.directions.length);

function dirSuffix(dir: Direction): string {
  return HAS_DIRECTIONS ? `-${dir}` : '';
}

export function bodyPath(id: string, dir: Direction = 's'): string {
  return `${ROOT}/body/${id}${dirSuffix(dir)}.png`;
}

export function eyesPath(id: string, dir: Direction = 's'): string | null {
  if (!id || id === 'none') return null;
  return `${ROOT}/eyes/${id}${dirSuffix(dir)}.png`;
}

export function hairPath(styleId: string, hairColor: string, dir: Direction = 's'): string {
  return `${ROOT}/hair/${styleId}/${hairColor}${dirSuffix(dir)}.png`;
}

/** Look up the (baseId, variant) split for a flattened category id. */
function lookupVariantEntry(category: string, compoundId: string): { baseId: string; variant: string } | null {
  if (!compoundId || compoundId === 'none') return null;
  const cat = MANIFEST.categories[category];
  if (!cat) return null;
  const entry = cat.values.find((v) => v.id === compoundId);
  if (!entry) return null;
  const baseId = entry.baseId ?? compoundId;
  const variant = entry.variant ?? 'default';
  return { baseId, variant };
}

function buildVariantPath(category: string, compoundId: string, dir: Direction): string | null {
  const split = lookupVariantEntry(category, compoundId);
  if (!split) return null;
  return `${ROOT}/${category}/${split.baseId}/${split.variant}${dirSuffix(dir)}.png`;
}

export function outfitPath(id: string, dir: Direction = 's'): string | null {
  return buildVariantPath('outfit', id, dir);
}
export function accessoryPath(id: string, dir: Direction = 's'): string | null {
  return buildVariantPath('accessory', id, dir);
}

export const SPRITE_DIMS = {
  width: MANIFEST.spriteWidth,
  height: MANIFEST.spriteHeight,
  bustCrop: MANIFEST.bustCrop,
  defaultDirection: (MANIFEST.defaultDirection ?? 's') as Direction,
} as const;

// Re-export manifest itself for the OG route (Node-side) to read.
export { MANIFEST as _MANIFEST };
