// Trait catalog adapter — thin layer over public/sprites/manaseed/manifest.json.
//
// The manifest is generated by `scripts/import-manaseed.mjs` from the
// vendored Mana Seed Character Base pack. Adding/removing trait options
// is a manifest change, not a code change.

import type { Category, TrainerConfig, TrainerOption } from '@/types/trainer';
import manifest from '../../public/sprites/manaseed/manifest.json';

// ---- manifest types (loose — matches the generated JSON shape) ----
interface ManifestValue {
  id: string;
  label?: string;
  file?: string;
  baseId?: string;     // for outfit/hat/cloak/face: source ID before -<variant> suffix
  variant?: string;    // for outfit/hat/cloak/face: the variant suffix (e.g. 'v01')
  hex?: string;
}
interface ManifestCategory {
  values: ManifestValue[];
  optional?: boolean;
  supportsColor?: boolean;
}
interface Manifest {
  version: number;
  source?: string;
  spriteWidth: number;
  spriteHeight: number;
  bustCrop: { x: number; y: number; w: number; h: number };
  categories: Record<string, ManifestCategory>;
}
const MANIFEST = manifest as Manifest;

// ---- public surface ----

export interface TraitCategory {
  key: keyof TrainerConfig;
  label: string;
  options: TrainerOption[];
  /** True when the user MUST pick a value before Generate is allowed. */
  required: boolean;
}

const CATEGORY_LABELS: { key: keyof TrainerConfig; label: string }[] = [
  { key: 'body',      label: 'Skin' },
  { key: 'hair',      label: 'Hair' },
  { key: 'hairColor', label: 'Hair Color' },
  { key: 'outfit',    label: 'Outfit' },
  { key: 'cloak',     label: 'Cloak' },
  { key: 'face',      label: 'Face' },
  { key: 'hat',       label: 'Hat' },
];

// Required-for-generate categories — empty string blocks Generate.
// Optional categories use 'none' as the "not picked" sentinel.
export const REQUIRED_FOR_GENERATE: ReadonlyArray<keyof TrainerConfig> = [
  'body', 'hair', 'hairColor', 'outfit',
];

const REQUIRED_SET: ReadonlySet<string> = new Set<string>(REQUIRED_FOR_GENERATE as readonly string[]);

function manifestToOptions(cat: ManifestCategory | undefined): TrainerOption[] {
  if (!cat) return [];
  return cat.values.map((v) => ({ id: v.id, label: v.label ?? v.id }));
}

export const CATEGORIES: TraitCategory[] = CATEGORY_LABELS.map(({ key, label }) => {
  const cat = MANIFEST.categories[key as Category];
  return {
    key,
    label,
    options: manifestToOptions(cat),
    required: REQUIRED_SET.has(key),
  };
});

export const INITIAL_CONFIG: TrainerConfig = {
  body: '',
  hair: '',
  hairColor: '',
  outfit: '',
  cloak: 'none',
  face: 'none',
  hat: 'none',
};

export function isReadyToGenerate(config: TrainerConfig): boolean {
  for (const key of REQUIRED_FOR_GENERATE) {
    const value = config[key];
    if (!value || value === 'none') return false;
  }
  return true;
}

// ---- sprite-path helpers ----
//
// Mana Seed paper-doll layer paths (per Seliel's `using this base.txt`,
// rendered lowest-first):
//   body     /sprites/manaseed/body/<bodyId>.png
//   outfit   /sprites/manaseed/outfit/<baseId>/<variant>.png
//   cloak    /sprites/manaseed/cloak/<baseId>/<variant>.png
//   face     /sprites/manaseed/face/<baseId>/<variant>.png
//   hair     /sprites/manaseed/hair/<style>/<hairColor>.png
//   hat      /sprites/manaseed/hat/<baseId>/<variant>.png
//
// Outfit/cloak/face/hat option IDs from the manifest are `<baseId>-<variant>`
// so the renderer must split on '-' to build the file path.

const ROOT = '/sprites/manaseed';

export function bodyPath(id: string): string {
  return `${ROOT}/body/${id}.png`;
}
export function hairPath(styleId: string, hairColor: string): string {
  return `${ROOT}/hair/${styleId}/${hairColor}.png`;
}

/** Resolve `<baseId>-<variant>` (e.g. "fstr-v02") into baseId + variant. */
function splitVariantId(compoundId: string): { baseId: string; variant: string } | null {
  const idx = compoundId.lastIndexOf('-');
  if (idx <= 0) return null;
  return { baseId: compoundId.slice(0, idx), variant: compoundId.slice(idx + 1) };
}

function buildVariantPath(category: string, compoundId: string): string | null {
  if (!compoundId || compoundId === 'none') return null;
  const split = splitVariantId(compoundId);
  if (!split) return null;
  return `${ROOT}/${category}/${split.baseId}/${split.variant}.png`;
}

export function outfitPath(id: string): string | null { return buildVariantPath('outfit', id); }
export function cloakPath(id: string):  string | null { return buildVariantPath('cloak',  id); }
export function facePath(id: string):   string | null { return buildVariantPath('face',   id); }
export function hatPath(id: string):    string | null { return buildVariantPath('hat',    id); }

export const SPRITE_DIMS = {
  width: MANIFEST.spriteWidth,
  height: MANIFEST.spriteHeight,
  bustCrop: MANIFEST.bustCrop,
} as const;

// Re-export manifest itself for the OG route (Node-side) to read.
export { MANIFEST as _MANIFEST };
